"""Evaluation report generation."""

from gauntlet.reporting.canonical import (
    CanonicalAssertionResult,
    CanonicalEvaluation,
    CanonicalEvidencePayload,
    CanonicalFinding,
    CanonicalizationError,
    CanonicalRepeat,
    CanonicalScenarioResult,
    ScenarioEvaluationRecord,
    canonical_repeat_digest,
)
from gauntlet.reporting.compare import (
    ComparisonArtifactError,
    ComparisonInputError,
    ContextChange,
    ContextChangeKind,
    NumericDelta,
    RegressionAssessment,
    RunComparison,
    RunComparisonService,
    format_run_comparison,
)
from gauntlet.reporting.generator import ReportGenerationError, ReportGenerator
from gauntlet.reporting.models import (
    BenchmarkProvenance,
    ExecutionMode,
    LiveRepeatDistribution,
    ReportArtifacts,
    ReportContext,
    ReproducibilityClaim,
    ReproducibilityReport,
    RunSummary,
)
from gauntlet.reporting.pipeline import (
    EvaluationConfigurationError,
    EvaluationExecutionError,
    EvaluationExitCode,
    EvaluationPipeline,
    EvaluationPipelineError,
    EvaluationPipelineResult,
    EvaluationRequest,
    EvaluationSecurityError,
    IncompleteEvaluationError,
    exit_code_for_recommendation,
)

__all__ = [
    "BenchmarkProvenance",
    "CanonicalAssertionResult",
    "CanonicalEvaluation",
    "CanonicalEvidencePayload",
    "CanonicalFinding",
    "CanonicalRepeat",
    "CanonicalScenarioResult",
    "CanonicalizationError",
    "ComparisonArtifactError",
    "ComparisonInputError",
    "ContextChange",
    "ContextChangeKind",
    "EvaluationConfigurationError",
    "EvaluationExecutionError",
    "EvaluationExitCode",
    "EvaluationPipeline",
    "EvaluationPipelineError",
    "EvaluationPipelineResult",
    "EvaluationRequest",
    "EvaluationSecurityError",
    "ExecutionMode",
    "IncompleteEvaluationError",
    "LiveRepeatDistribution",
    "NumericDelta",
    "RegressionAssessment",
    "ReportArtifacts",
    "ReportContext",
    "ReportGenerationError",
    "ReportGenerator",
    "ReproducibilityClaim",
    "ReproducibilityReport",
    "RunSummary",
    "RunComparison",
    "RunComparisonService",
    "ScenarioEvaluationRecord",
    "canonical_repeat_digest",
    "exit_code_for_recommendation",
    "format_run_comparison",
]
